config/routes.rb
Rails.application.routes.draw do
  resources :books_controller
  root :to => 'homes#top'
  post 'books' => 'books#create'
  get 'books' => 'books#index'
  get 'books/:id' => 'books#show',as: 'book'
  get 'books/:id/edit' =>'books#edit',as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def create
    @book = Book.new(book_params)
    flash[:notice] = "Book was successfully created."
    if @book.save
    redirect_to book_path(@book.id)
   else
    @books =Book.all
    render :index
   end
  end
 
  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book=Book.find(params[:id])
  end
  
  def update
    @book=Book.find(params[:id])
    @book.update(book_params)
    
    flash[:notice] = "Book was successfully updated."
     if @book.save
    redirect_to book_path(@book.id)
    else
    render :edit
    end
    
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<body>
  <style type="text/css">


 body {font-family: ;verdana, arial, helvetica, sans-serif;
       font-size: 13px;
       line-height: 18px;
       margin: 33px;
 }

 p {margin-bottom: 10px;
  
 }
  
 ul {padding-left: 0px;
   
 }
 
 ul li {display: inline-block;
   
 }

 li:not(:first-child)::before {content: "｜";
    
 }
      
 </style>

 <h1>Editing Book</h1>
 
 <% if @book.errors.any? %>
　<%= @book.errors.count %>error prohibited this book from being saved:
　 <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
 <% end %>
 
 <%= form_with model: @book,url: update_book_path(@book.id),method: :patch do |f| %>

 <p>Title</p>
 <%= f.text_field :title %>

 <p>Body</p>
 <%= f.text_area :body %>


 <p><%= f.submit 'Update Book' %></p>

 <% end %>
 <ul>
 　<li><%= link_to "Show",book_path(@book.id) %></li>
 　<li><%= link_to "Back","/books" %></li>
 </ul>
</body>

app/views/books/index.html.erb
<body>
<style type="text/css">
  body { margin: 33px;
        font-size: 13px;
        font-family: verdana,arial,helvetica,sans-serif;
        line-height: 18px;
    }

  h1 {margin: 17.42px 0px;


  }

  th {padding-bottom: 5px;
      display: table-cell;
      vertical-align: inherit;
      font-weight: bold;
      text-align: center;
  }

  td {padding-bottom: 7px;
      padding-left: 5px;
      padding-right: 5px;
      white-space: nowrap;
  }

  p {margin-bottom: 10px;
     margin-top: 0px;
  }


</style>

<h1>Books</h1>
<table>
　<thead>
  　<tr>
    　<th>Title</th>
    　<th>Body</th>
    　<th></th>
  　</tr>
　</thead>

　<tbody>
  　<% @books.each do |book| %>

 　 <tr>
    　<td align="left"><%= book.title %></td>
    　<td align="left"><%= book.body %></td>
    　<td><%= link_to "Show",book_path(book.id) %></td>
    　<td><%= link_to "Edit",edit_book_path(book.id) %></td>
    　<td><%= link_to "Destroy",destroy_book_path(book.id),method: :delete,"data-confirm" => "Are you sure?" %></td>
 　 </tr>
 　 <% end %>
　</tbody>
　</table>

<h2>New book</h2>
<% if @book.errors.any? %>
　<%= @book.errors.count %>error prohibited this book from being saved:
　 <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
　<%= form_with model: @book,url: '/books', method: :post do |f| %>
　<p>Title<br>
　<%= f.text_field :title %>
  </p>
　<p>Body<br>
　<%= f.text_area :body %>
  </p>
　<p><%= f.submit 'Create Book' %></p>

　<% end %>
</body>

app/views/books/show.html.erb
<body>
  <style type="text/css">
    body {font-family: verdana, arial, helvetica, sans-serif;
          font-size: 13px;
          line-height: 18px;
          margin: 33px;
    }

    p {margin: 33px;

    }


    ul  {padding-left: 0px;

    }

    ul li {display: inline-block;}

    li:not(:first-child)::before {content: "｜";

    }

  </style>

 <% if flash[:notice] %>
 <p id="notice">
   <%= flash[:notice] %>
 </p>
 <% end %>

 <p>
   <strong>Title:</strong>
   <%= @book.title %>
 </p>

 <p>
   <strong>Body:</strong>
   <%= @book.body %>
 </p>

 <ul>
  <li><%= link_to "Edit",edit_book_path(@book.id) %></li>
  <li><%= link_to "Back","/books" %></li>
 </ul>
</body>

app/views/homes/top.html.erb
<body>
  <style type="text/css">
    
    body { margin: 33px;
    }
    
    h1 { font-family: verdana,arial,helvetica,sans-serif;
         margin: 17.42px 0px;
    }
    
    p {  font-family: verdana,arial,helvetica,sans-serif;
         margin: 33px;
    }   
  
  </style>
  <h1>
    ようこそ 
    <strong>Bookers</strong>
     へ！
  </h1>
  <p>
    <strong>Bookers</strong>
    では、さまざまな書籍に関するあなたの意見や
  </p>
  <p>印象を共有し交換することができます</p>
  
  <p><%= link_to "start","/books" %></p>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>